name: ultraplot-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.15
  - numpy
  - matplotlib>=3.9
  - basemap >=1.4.1
  - cartopy
  - xarray
  - seaborn
  - pandas
  - pytest
  - pytest-mpl
  - pytest-cov
  - pytest-xdist
  - pip
  - pint
  - pre-commit
  - networkx
  - pyarrow
  - cftime
  - pip:
      - pycirclize
